### ISSUE TITLE
wrong revision for uboot?

### ISSUE THREAD

**Issue by zhangn1985** [khadas/buildroot_manifest#1]
`<project name="u-boot" path="bootloader/uboot-2015-dev" revision="b3c8a29fe1faf04010398d49d51488f103250cb7"/>`

should be:

` <project name="u-boot" path="bootloader/uboot-2015-dev" revision="879772bd9eedac7c49080bcc4678c558c47540c2"/>`

or just default revision?

**Comment by numbqq** [comment]
Hello zhangn1985,

Yes, you're right, it should be `879772bd9eedac7c49080bcc4678c558c47540c2`. It's a mistake...

**Comment by zhangn1985** [comment]
@numbqq 从这个Buildroot编译出来的image，能正常启动到UI吗？开发到何种程度了？
我简单看了一下uboot, kernel，都只是有basic support？

**Comment by numbqq** [comment]
Hello @zhangn1985,

基本上是Amlogic提供的原生的，没有做过多修改，只是简单适配了下VIMs，没有怎么维护的。

**Comment by zhangn1985** [comment]
@numbqq 编译出来的 aml_upgrade_package.img 可以通过 https://docs.khadas.com/vim1/CreateBurnCardViaCLI.html 这个方法刷到eMMC吗？

**Comment by numbqq** [comment]
这个没有测试过，只通过T卡烧录过Android。

**Comment by zhangn1985** [comment]
![default](https://user-images.githubusercontent.com/832666/44100911-b28b365c-a018-11e8-9194-f462ddb2fb91.png)

按照这里的说法是windows是用USB burn tool, linux 是用aml_update_whole_package.sh，但其语焉不详，我从你们的文档中发现有类似但不同，https://docs.khadas.com/vim1/UpgradeViaUSBCable.html
其中Linux的方法略有不同，主要体现在工具上。 aml_upgrade_package.img 可以用aml-burn-tool 烧到eMMC吗？

**Comment by numbqq** [comment]
> aml_upgrade_package.img 可以用aml-burn-tool 烧到eMMC吗

可以的。

Amlogic Buildroot文档里面说的那个烧录脚本都没找到，都不完整的，所以都没用过。

**Comment by zhangn1985** [comment]
谢谢啦。
